#!/bin/sh
# Copyright (c) 2014, Able Pear Software. All rights reserved.
# Distributed under the GNU General Public License, version 3.

cd `dirname $0`

PROJECT_DIR="`pwd`"
BUILD_DIR="$PROJECT_DIR/build"

xcodebuild \
	-project WgetInstaller.xcodeproj \
	-scheme WgetInstaller \
	-configuration Release \
	SYMROOT="$BUILD_DIR" \
	OBJROOT="$BUILD_DIR"
